# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 04:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('radius', models.FloatField()),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rider.Rider')),
            ],
        ),
    ]
