# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.IntegerField()),
                ('complex_id', models.IntegerField()),
                ('gtfs_stop_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('division', models.CharField(max_length=3)),
                ('line', models.CharField(max_length=128)),
                ('stop_name', models.CharField(max_length=128)),
                ('borough', models.CharField(max_length=3)),
                ('structure', models.CharField(max_length=128)),
                ('gtfs_lat', models.DecimalField(decimal_places=9, max_digits=12)),
                ('gtfs_lon', models.DecimalField(decimal_places=9, max_digits=12)),
            ],
        ),
    ]
